
ID:=$(shell id -u)

# We use pthreads in a lot of things
PTHREADS=yes

ifeq ($(ID),0)
PREFIX?=/opt/sd
else
PREFIX?=$(shell echo ~)
endif

# Define SRC_ROOT
current_makefile := $(lastword $(MAKEFILE_LIST))
SRC_ROOT=$(shell echo $$(dirname $(current_makefile)))

include $(SRC_ROOT)/make.opts

ifeq ($(RELEASE),yes)
DEBUG=no
DEBUG_MEM=no
LIBTYPE=shared
endif

TOOLS?=$(SRC_ROOT)/tools

# Static build requires standard lib
ifeq ($(STATIC),yes)
	LIBTYPE=standard
endif

# We need to define LIBEXT for DEPS
ifeq ($(LIBTYPE),shared)
	ifneq "$(findstring win,$(TARGET))" ""
		LIBEXT=.dll
	else
		LIBEXT=.so
	endif
else
	LIBEXT=.a
endif

ifeq ($(JS),yes)
	_NJ=-js
endif
ifeq ($(MQTT),yes)
	_NM=-mqtt
endif
ifeq ($(INFLUX),yes)
	_NI=-influx
endif
LIBSDNAME=sd$(_NJ)$(_NM)$(_NI)
ifneq ($(LIBSD),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/sd
	LIBS+=-L$(SRC_ROOT)/lib/sd -l$(LIBSDNAME)$(LIBSUFFIX)
	DEPS+=$(SRC_ROOT)/lib/sd/lib$(LIBSDNAME)$(LIBSUFFIX)$(LIBEXT)
	MATH=yes
endif

ifeq ($(JS),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/js -DJS
	LIBS+=-L$(SRC_ROOT)/lib/js -ljs
	MATH=yes
	DEPS+=$(SRC_ROOT)/lib/js/libjs$(LIBEXT)
#	ifeq ($(OS),Windows)
	ifneq "$(findstring win,$(TARGET))" ""
		CFLAGS+=-DXP_WIN
	else
		CFLAGS+=-DXP_UNIX
	endif
	NEED_LIBSD=yes
endif

ifeq ($(SMANET),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/smanet -DSMANET
	LIBS+=-L$(SRC_ROOT)/lib/smanet -lsmanet$(_NJ)
	DEPS+=$(SRC_ROOT)/lib/smanet/libsmanet$(_NJ)$(LIBEXT)
	NEED_LIBSD=yes
endif

# Bluetooth
ifeq ($(BLUETOOTH),yes)
	ifneq ($(OS),Windows)
		CFLAGS+=-DBLUETOOTH
		LIBS+=-L$(SRC_ROOT)/lib/bt -lbt -lgattlib -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lbluetooth
		NEED_LIBSD=yes
	endif
endif

ifeq ($(WPI),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/wpi
	ifneq ("$(wildcard //usr/local/include/wiringPi.h)","")
		CFLAGS+=-DWPI
		LIBS+=-L$(SRC_ROOT)/lib/wpi -lwpi$(_NJ) -lwiringPi -lwiringPiDev
		DEPS+=$(SRC_ROOT)/lib/wpi/libwpi$(_NJ)$(LIBEXT)
	endif
endif


ifeq ($(NEED_LIBSD),yes)
	LIBS+=-L$(SRC_ROOT)/lib/sd -l$(LIBSDNAME)$(LIBSUFFIX)
endif

include $(SRC_ROOT)/Makefile.sys

main.o: $(SRCS)
	@mkdir -p .deps
	@echo "#define __SD_BUILD $$(date '+%Y%m%d%H%M')" > __sd_build.h
	$(FULLCC) -c main.c
