
ID:=$(shell id -u)

# We use pthreads in a lot of things
PTHREADS=yes

PREFIX?=/opt/sd

#ifeq ($(ID),0)
#PREFIX?=/opt/sd
#else
#PREFIX?=$(shell echo ~)
#endif

# Define SRC_ROOT
current_makefile := $(lastword $(MAKEFILE_LIST))
SRC_ROOT=$(shell echo $$(dirname $(current_makefile)))

include $(SRC_ROOT)/make.opts

# Local user overrides (loaded last so they can override anything)
ifneq ("$(wildcard ~/.sd_make_opts)","")
include ~/.sd_make_opts
endif

ifeq ($(RELEASE),yes)
DEBUG=no
DEBUG_MEM=no
LIBTYPE=shared
endif

TOOLS?=$(SRC_ROOT)/tools

# Static build requires standard lib
ifeq ($(STATIC),yes)
	LIBTYPE=standard
endif

# We need to define LIBEXT for DEPS
ifeq ($(LIBTYPE),shared)
	ifneq "$(findstring win,$(TARGET))" ""
		LIBEXT=.dll
	else
		LIBEXT=.so
	endif
else
	LIBEXT=.a
endif

ifeq ($(JS),yes)
	_NJ=-js
endif
ifeq ($(MQTT),yes)
	_NM=-mqtt
endif
ifeq ($(INFLUX),yes)
	_NI=-influx
endif
# Library directory: local build cache if BUILDROOT set, else source tree
# Uses lazy evaluation (=) so _BUILD_BASE from Makefile.sys resolves at use time
_SD_LIBDIR = $(if $(_BUILD_BASE),$(_BUILD_BASE),$(SRC_ROOT))

LIBSDNAME=sd$(_NJ)$(_NM)$(_NI)
ifneq ($(LIBSD),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/sd
	LIBS+=-L$(_SD_LIBDIR)/lib/sd -l$(LIBSDNAME)$(LIBSUFFIX)
	DEPS+=$(_SD_LIBDIR)/lib/sd/lib$(LIBSDNAME)$(LIBSUFFIX)$(LIBEXT)
	MATH=yes
endif

ifeq ($(JS),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/js -DJS
	LIBS+=-L$(_SD_LIBDIR)/lib/js -ljs
	MATH=yes
	DEPS+=$(_SD_LIBDIR)/lib/js/libjs$(LIBEXT)
	ifneq "$(findstring win,$(TARGET))" ""
		CFLAGS+=-DXP_WIN
	else
		CFLAGS+=-DXP_UNIX
	endif
	NEED_LIBSD=yes
endif

ifeq ($(SMANET),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/smanet -DSMANET
	LIBS+=-L$(_SD_LIBDIR)/lib/smanet -lsmanet$(_NJ)
	DEPS+=$(_SD_LIBDIR)/lib/smanet/libsmanet$(_NJ)$(LIBEXT)
	NEED_LIBSD=yes
endif

# Bluetooth
ifeq ($(BLUETOOTH),yes)
	ifneq ($(OS),Windows)
        CFLAGS+=-DBLUETOOTH `pkg-config --cflags glib-2.0 gio-2.0`
        LIBS+=`pkg-config --libs glib-2.0 gio-2.0` -lbluetooth
        # XXX in order to static link on my RPI4 64-bit debian 11 box
        # download https://github.com/util-linux/util-linux
        # ./configure --disable-shared --enable-static
        # make
        # cp ./.libs/libmount.a /usr/lib/aarch64-linux-gnu/
        ifeq ($(STATIC),yes)
                LIBS+=-lffi -lpcre -lpthread -lmount -ldl -lblkid -lresolv -lz -lselinux
        endif
		NEED_LIBSD=yes
	endif
endif

ifeq ($(WPI),yes)
	CFLAGS+=-I$(SRC_ROOT)/lib/wpi
	ifneq ("$(wildcard /usr/local/include/wiringPi.h)","")
		CFLAGS+=-DWPI
		LIBS+=-L$(_SD_LIBDIR)/lib/wpi -lwpi$(_NJ) -lwiringPi -lwiringPiDev
		DEPS+=$(_SD_LIBDIR)/lib/wpi/libwpi$(_NJ)$(LIBEXT)
	endif
endif


ifeq ($(NEED_LIBSD),yes)
	LIBS+=-L$(_SD_LIBDIR)/lib/sd -l$(LIBSDNAME)$(LIBSUFFIX)
endif

include $(SRC_ROOT)/Makefile.sys

$(_OP)main$(OBJSUFFIX).o: $(SRCS)
	@mkdir -p $(DEPDIR)
	@echo "#define __SD_BUILD $$(date '+%Y%m%d%H%M')" > $(_OP)__sd_build.h
	$(CC) -MT $@ -MMD -MP -MF $(DEPDIR)/main$(OBJSUFFIX).d $(CFLAGS) -c main.c -o $@
