
PROGNAME=jbd
SRCS=main.c driver.c config.c info.c jsfuncs.c
CFLAGS+=-DTARGET_ENDIAN=BIG_ENDIAN

JS=no
MQTT=yes
INFLUX=yes

include ../../Makefile.sd

#LIBS+=$(shell krb5-config --libs)
#LIBS+=-L/usr/lib64/heimdal -lkrb5 -lhcrypto -lhx509 -lasn1 -lheimbase -lroken -lsqlite3
