
PROGNAME=$(shell basename $(shell pwd))
SRCS=main.c

JS=no
INFLUX=no

include ../../Makefile.sd

#install:
#	sudo mkdir -p $(BINDIR)
#	sudo install -m 755 -o root -g root cellmon $(BINDIR)
#	sudo mkdir -p $(ETCDIR)
#	sudo install -m 644 -o root -g root cellmon.conf $(ETCDIR)

