
PROGNAME=si
SRCS=main.c can.c smanet.c info.c driver.c siconfig.c jsfuncs.c
SCRIPTS=*.js

SERVICE_NAME=si
SERVICE_DESC=Sunny Island Agent

# JS is pretty much a req for SI at this point
JS=yes
SMANET=yes

include ../../Makefile.sd
