#!/bin/bash

tmp=/tmp/sdmem.$$
trap '{ rm -f $tmp; }' EXIT

HFORMAT="%10.10s  %4.4s  %4.4s  %10.10s  %10.10s  %s\n"
DFORMAT="%10d  %4.1f  %4.1f  %10d  %10d  %s\n"
TFORMAT="%10s  %4.1f  %4.1f  %10d  %10d  %s\n"

echo ""
date
#ps uax | grep USER | grep -v grep
printf "$HFORMAT" "PID" "%CPU" "%MEM" "VSZ" "RSS" "PROG"
printf "$HFORMAT" "-----------" "------" "-------" "------------------" "----------------" "-----------------------------------------------------------------------------"
ps uax | grep \/opt\/sd | grep -v -e grep -e bin/sdmem > $tmp
tcpu="0.0"
tmem="0.0"
tvsz="0"
trss="0"
while read user pid pcpu pmem pvsz prss rest
do
	prog=$(echo "$rest" | awk '{ i=index($0,"/opt/sd"); print substr($0,i,99); }')
	printf "$DFORMAT" $pid $pcpu $pmem $pvsz $prss "$prog"
	tcpu=$(echo "$tcpu + $pcpu" | /usr/bin/bc);
	tmem=$(echo "$tmem + $pmem" | /usr/bin/bc);
	tvsz=$(echo "$tvsz + $pvsz" | /usr/bin/bc);
	trss=$(echo "$trss + $prss" | /usr/bin/bc);
done < $tmp
printf "$HFORMAT" "-----------" "------" "-------" "------------------" "----------------"
printf "$TFORMAT" "Total" "$tcpu" "$tmem" "$tvsz" "$trss"
